### ISSUE TITLE
HTTP 502

### ISSUE THREAD

**Issue by kamilmielnik** [kamilmielnik/scrabble-solver#235]
https://github.com/kamilmielnik/scrabble-solver/issues/225#issuecomment-1445175775

> Also your website is no longer working.

----

Happened again today.

**Comment by kamilmielnik** [comment]
Happened again today.

Check this log before restarting service next time: `cat /var/log/scrabble-solver/log.log`

**Comment by kamilmielnik** [comment]
That's the log:

```Shell
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.end (node:_http_outgoing:985:15)
    at apiRes.end (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/node.js:356:25)
    at Object.sendError (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/index.js:115:9)
    at Object.apiResolver (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/node.js:390:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:513:9)
    at async Object.fn (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:815:35)
    at async Router.execute (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:375:20)
    at async /projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:157:99
Emitted 'error' event on ServerResponse instance at:
    at emitErrorNt (node:_http_outgoing:846:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

```

**Comment by kamilmielnik** [comment]
https://github.com/vercel/next.js/issues/17574#issuecomment-705542288

**Comment by kamilmielnik** [comment]
```
error: verify - error {"error":{},"meta":{"userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534+ (KHTML, like Gecko) BingPreview/1.0b","xForwardedFor":"40.77.202.176","xRealIp":"40.77.202.176"},"timestamp":"2023-03-11 18:48:22"}
Error: Invalid "locale" parameter
    at parseRequest (/projects/scrabble-solver/packages/scrabble-solver/.next/server/pages/api/verify.js:179:15)
    at verify (/projects/scrabble-solver/packages/scrabble-solver/.next/server/pages/api/verify.js:144:37)
    at Object.apiResolver (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/node.js:372:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:375:20)
    at async /projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:157:99
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.end (node:_http_outgoing:985:15)
    at apiRes.end (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/node.js:356:25)
    at Object.sendError (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/index.js:115:9)
    at Object.apiResolver (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/api-utils/node.js:390:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:432:29)
    at async NextNodeServer.handleRequestImpl (/projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:375:20)
    at async /projects/scrabble-solver/packages/scrabble-solver/node_modules/next/dist/server/base-server.js:157:99
Emitted 'error' event on ServerResponse instance at:
    at emitErrorNt (node:_http_outgoing:846:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

```

**Comment by kamilmielnik** [comment]
[Moving to vercel would probably fix this for good](https://github.com/kamilmielnik/scrabble-solver/issues/248#issuecomment-1465823822).

For now, perhaps not rethrowing errors will help.

**Comment by kamilmielnik** [comment]
Deployed, monitoring.
This used to happen every 5 days on average.

**Comment by kamilmielnik** [comment]
It happened 2 times this month already.

**Comment by kamilmielnik** [comment]
Possibly related: #307

**Comment by kamilmielnik** [comment]
```
cat /var/log/scrabble-solver/log.log

> @scrabble-solver/scrabble-solver@2.12.3 start
> env-cmd next start -p 3333

ready - started server on 0.0.0.0:3333, url: http://localhost:3333
info  - Loaded env from /projects/scrabble-solver/packages/scrabble-solver/.env
Killed
```

**Comment by kamilmielnik** [comment]
Perhaps it dies out of memory. There's < 100MB left. Added 2GB extra today. Let's see if it helps.

**Comment by kamilmielnik** [comment]
There have been no crashes since adding more RAM to the server. Solved.
